### ISSUE TITLE
Readme.md file could include more information, additional formatting.

### ISSUE THREAD

**Issue by rboothneu** [kerry-snyder/GIS6345_Week3Assignment#1]
@kerry-snyder  - Nice repo!  You might think about adding more information to it, linking to the scripts, etc...
This is a good resource for writing Markdown, the text formatting language used in GitHub (and elsewhere).
https://www.markdownguide.org/cheat-sheet/

**Comment by kerry-snyder** [comment]
Thanks! I added some extra information.
