### ISSUE TITLE
Typo in variable name fermet should be fermat

### ISSUE THREAD

**Issue by rboothneu** [kerry-snyder/GIS6345_Week3Assignment#2]
You misspelled Fermat in your variable name.

https://github.com/kerry-snyder/GIS6345_Week3Assignment/blob/c6e2ef1b3d231a7e38e53b1da4b8b9913566e700/Week3Assignment_KSnyder_Exercise5.2.py#L2

@kerry-snyder

**Comment by kerry-snyder** [comment]
Fixed! Thank you.
